[tool.poetry]
name = "pubsub"
version = "0.1.0"
description = ""
authors = ["luiz zamboni"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
google-cloud-pubsub = "^2.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
